env:
  global:
  - DEBUG='* -mocha:* -superagent -express:* -base:validator -base:entity'
language: node_js
node_js:
- '6.9.0'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  global:
  - CXX=g++-4.8

cache:
  yarn: true
  directories:
    - node_modules

# encrpyt channel name to get around issue
# https://github.com/travis-ci/travis-ci/issues/1094
notifications:
  irc:
    channels:
      # encrpyted string was "irc.mozilla.org#taskcluster-bots"
      - secure: "GCcDt7IVSe8jPC0QfUgCVpkESeZZ/ThAA7+BoF30rHGDWXbOzu4dMXjT8D7/cC+y6nhh6mgueYPtxg+mdWVBMwUwncMSc+4BiMBQykF596b/yxqM/UlKs5y1in+7xhQ6+hNZL/EzICcq10XXQT9bTuRf2Oa/jdpQwddzwnCSoqQ="
    on_success: change
    on_failure: always
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
      - "Commit message : %{commit_message}"
