defaults:
  taskcluster:
    rootUrl:        https://taskcluster-events-staging.herokuapp.com/ 
    credentials:
      clientId:     !env TASKCLUSTER_CLIENT_ID
      accessToken:  !env TASKLCSUTER_ACCESS_TOKEN
  
  server:
    port:           !env:number PORT
    env:            !env NODE_ENV
    forceSSL:       !env:flag FORCE_SSL
    trustProxy:     false
  
  monitor:
    mock:           true
    enable:         !env:bool MONITORING_ENABLE
  
  pulse:
    username:       !env PULSE_USERNAME
    password:       !env PULSE_PASSWORD
    hostname:       !env PULSE_HOSTNAME
    vhost:          !env PULSE_VHOST


production:
  server:
    env:            production
    trustProxy:     true

  monitor:
    mock:           false

test:
  taskcluster:
    rootUrl:        http://localhost:12345

  monitor:
    enable:         false

  server:
    port:           12345
    env:            development

  pulse:
    username:       !env PULSE_USERNAME
    password:       !env PULSE_PASSWORD
    hostname:       pulse.mozilla.org
    vhost:          /

